version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: fluctux-web
    env_file:
      - .env
    ports:
      - "3002:3000"
    restart: always
    depends_on:
      - mongoDb

  mongoDb:
    image: mongo
    container_name: fluctux-database
    ports:
      - "27017:27017"
    volumes:
      - fluctux_database:/data/db
    restart: always

volumes:
  fluctux_database:
