import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import global style
import "@fluctux/tailwind-config/index.css";
import "./local.css";

import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { TooltipProvider } from "@fluctux/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Admin",
    default: "Admin",
  },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-hidden`}
      >
        <Suspense>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SkeletonTheme
              baseColor="var(--skeleton-base-color)"
              highlightColor="var(--skeleton-highlightColor)"
            >
              <TooltipProvider>{children}</TooltipProvider>
            </SkeletonTheme>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
