import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";

import "./styles/global.css";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { MainWrapper } from "@/components/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} dark:!bg-black !bg-white w-full h-screen overflow-hidden p-1.5`}
      >
        <ThemeProvider attribute="class">
          <Suspense>
            <SkeletonTheme
              baseColor="var(--skeleton-base-color)"
              highlightColor="var(--skeleton-highlightColor)"
            >
              <MainWrapper>{children}</MainWrapper>
            </SkeletonTheme>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
