import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";

import "@fluctux/ui/styles/global.css";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { AsideRightComp, DocAppSidebar, MainContentWrapper } from "@/components/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} overflow-x-hidden`}
      >
        <ThemeProvider attribute="class">
          <Suspense>
            <SkeletonTheme
              baseColor="var(--skeleton-base-color)"
              highlightColor="var(--skeleton-highlightColor)"
            >
              <div className="max-w-[1400px] w-full mx-auto border-x border-border-color_1  flex justify-between items-start ">
                <DocAppSidebar />
                <MainContentWrapper>{children}</MainContentWrapper>
                <AsideRightComp/>
              </div>
            </SkeletonTheme>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
