import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/global.css";
import "./styles/workspace.style.css";
import "./styles/editor.style.css";
import "./styles/svg.style.css";
import "./styles/org.style.css";
import "./styles/alert.style.css";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { GlobalProviders } from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Fluctux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute="class">
          <Suspense>
            <GlobalProviders>
              <SkeletonTheme
                baseColor="var(--skeleton-base-color)"
                highlightColor="var(--skeleton-highlightColor)"
              >
                {children}
              </SkeletonTheme>
            </GlobalProviders>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
