name: 🐞 Bug Report
description: Report something that's broken or not working as expected
title: "[bug]: "
labels: [bug, triage]


body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Thanks for reporting a bug! Please help us fix it faster by filling out this form.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise title of the bug
      placeholder: e.g. Clicking Save does nothing
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce the bug step-by-step
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g. I expected the editor content to save successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: e.g. The page just reloads without saving the content
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: System or device info
      placeholder: e.g. macOS Sonoma, Chrome 122, Next.js 14, Node 20
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs / Errors
      description: If applicable, add screenshots, logs, or error messages
      placeholder: Paste any error output or screenshots here
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that might help us debug
      placeholder: e.g. Only happens after login, or when editing large content blocks
    validations:
      required: false
