name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the project
title: "[feat]: "
labels: [feature, needs-triage]


body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! Please fill out the details below.

  - type: input
    id: summary
    attributes:
      label: 📝 Feature Summary
      description: What would you like to add? Give a one-line summary of the feature.
      placeholder: e.g. Add dark mode support
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      value: |
        ## 📝 Feature Description
      label: Sample label
      description: Describe how the feature should work. Include details, potential API shape, or UI if applicable.
      placeholder: |
        e.g. Toggle switch in settings to enable dark mode; store preference in local storage.
    validations:
      required: true
