name: 🚀 Feature Request
description: Suggest an enhancement or new functionality for the project.
title: "[feat]: "
labels: [feature, triage]

body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A short, concise title for the feature.
      placeholder: e.g. Add dark mode to the application
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the problem this feature aims to solve or the value it would bring.
      placeholder: e.g. Users want a dark mode option for better accessibility.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Explain how the feature should work, including any expected behavior, UI design, or APIs.
      placeholder: e.g. Provide a toggle in settings to switch between light and dark modes.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: If any, describe alternatives or workarounds you’ve considered or tried.
      placeholder: e.g. A browser extension was used to achieve dark mode.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any extra information that could help in implementing the feature (e.g. design references, related issues, etc.)
      placeholder: e.g. Link to relevant design mockups, related issues, or documents.
    validations:
      required: false
