version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluctux-web
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - mongoDb

  mongoDb:
    image: mongo
    container_name: fluctux-database
    ports:
      - "27017:27017"
    volumes:
      - fluctux-database:/data/db
    restart: always

volumes:
  fluctux-database:
