import type { CellSelectorValuesType } from "@/components/ag-grid";

import type {
  ProductManageDataType,
  ProductsOverViewData,
  StatusLevelType,
} from "@/types";
import type { PopoverMenuDataType } from "@fluctux/ui";
import { FileIcon, ScanSearch, SlidersHorizontal, UploadIcon } from "lucide-react";

import {
  ShoppingBagIcon,
  MonitorIcon,
  ShirtIcon,
  UtensilsIcon,
  DumbbellIcon,
  HomeIcon,
  CarIcon,
  BookIcon,
  HeartIcon,
  GlobeIcon,
} from "lucide-react";

export const PRODUCT_PAGE_MENU_OPTIONS = {
  product: {
    data: [
      {
        label: "Product Options",
        value: "product-options",
        icon: SlidersHorizontal,
        isAsQueryParam: true,
      },
      {
        label: "Scrape Products",
        value: "scrape-products",
        icon: ScanSearch,
      }
    ],
  },
  export: {
    label: "Export",
    data: [
      { label: "Export CSV", value: "export-csv", icon: UploadIcon },
      { label: "Export PDF", value: "export-pdf", icon: FileIcon },
    ],
  },
} as const satisfies PopoverMenuDataType;

export type ProductMenuOptionsValuesType = NonNullable<
  (typeof PRODUCT_PAGE_MENU_OPTIONS)[keyof typeof PRODUCT_PAGE_MENU_OPTIONS]["data"]
>[number]["value"];

export const PRODUCTS_OVERVIEW_DATA: ProductsOverViewData[] = [
  { label: "Total Products", value: 1284 },
  { label: "In Stock", value: 978 },
  { label: "Out of Stock", value: 306 },
  { label: "Low stock", value: 306 },
];

export const DUMMY_STATUS_OPTIONS: CellSelectorValuesType<StatusLevelType>[] = [
  { value: "PUBLISHED", label: "Published", level: "SAFE" },
  { value: "DRAFT", label: "Draft", level: "WARNING" },
  { value: "TRASHED", label: "Trashed", level: "DESTRUCTIVE" },
];

export const DUMMY_STATUS_LEVEL: Record<StatusLevelType, string> = {
  SAFE: "bg-surface-green-bg! rounded-sm px-3 py-1 inset-ring-1 group-hover:bg-surface-green-bg-active! inset-ring-surface-green-border hover:inset-ring-1 text-rdx-green-fg hover:text-rdx-green-fg!",
  WARNING:
    "bg-surface-yellow-bg! rounded-sm px-3 py-1 inset-ring-1 group-hover:bg-surface-yellow-bg-active! inset-ring-surface-yellow-border hover:inset-ring-1 text-rdx-yellow-fg hover:text-rdx-yellow-fg!",
  DESTRUCTIVE:
    "bg-surface-red-bg! rounded-sm px-3 py-1 inset-ring-1 group-hover:bg-surface-red-bg-active! inset-ring-surface-red-border hover:inset-ring-1 text-rdx-red-fg hover:text-rdx-red-fg!",
};

// variations and attributes are currently in development
export const DUMMY_ROW_DATA: Omit<
  ProductManageDataType,
  "variations" | "attributes"
>[] = [
    {
      id: "prod_a1b2c3",
      name: "Wireless Noise-Cancelling Headphones",
      slug: "wireless-noise-cancelling-headphones",
      sku: "ELEC-001",
      regular_price: 129.99,
      sale_price: 109.99,
      discount: 15,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "admin",
      created_at: "2024-01-15",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_d4e5f6",
      name: "Slim Fit Denim Jacket",
      slug: "slim-fit-denim-jacket",
      sku: "CLTH-001",
      regular_price: 59.95,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Clothing",
          value: "clothing",
          icon: ShirtIcon,
          slug: "clothing",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-01-18",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_g7h8i9",
      name: "Stainless Steel Water Bottle",
      slug: "stainless-steel-water-bottle",
      sku: "HOME-001",
      regular_price: 24.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Sports", value: "sports", icon: DumbbellIcon, slug: "sports" },
      ],
      created_by: "admin",
      created_at: "2024-01-20",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_j1k2l3",
      name: "Mechanical Gaming Keyboard",
      slug: "mechanical-gaming-keyboard",
      sku: "ELEC-002",
      regular_price: 89.0,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "jane_smith",
      created_at: "2024-01-22",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_m4n5o6",
      name: "Yoga Mat Anti-Slip",
      slug: "yoga-mat-anti-slip",
      sku: "SPRT-001",
      regular_price: 34.5,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-01-25",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_p7q8r9",
      name: "Ceramic Coffee Mug Set",
      slug: "ceramic-coffee-mug-set",
      sku: "HOME-002",
      regular_price: 19.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "john_doe",
      created_at: "2024-01-28",
      status: { value: "TRASHED", label: "Trashed", level: "DESTRUCTIVE" },
    },
    {
      id: "prod_s1t2u3",
      name: "Portable Bluetooth Speaker",
      slug: "portable-bluetooth-speaker",
      sku: "ELEC-003",
      regular_price: 49.99,
      sale_price: 39.99,
      discount: 20,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        { label: "Travel", value: "travel", icon: GlobeIcon, slug: "travel" },
      ],
      created_by: "jane_smith",
      created_at: "2024-02-01",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_v4w5x6",
      name: "Running Shoes Ultra Boost",
      slug: "running-shoes-ultra-boost",
      sku: "SPRT-002",
      regular_price: 110.0,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-02-03",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_y7z8a9",
      name: "Smart Watch Series X",
      slug: "smart-watch-series-x",
      sku: "ELEC-004",
      regular_price: 249.99,
      sale_price: 199.99,
      discount: 20,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-02-05",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_b1c2d3",
      name: "Leather Wallet Slim",
      slug: "leather-wallet-slim",
      sku: "SHOP-001",
      regular_price: 39.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
          isPrimary: true,
        },
        {
          label: "Clothing",
          value: "clothing",
          icon: ShirtIcon,
          slug: "clothing",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-02-07",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_e4f5g6",
      name: "Organic Green Tea Pack",
      slug: "organic-green-tea-pack",
      sku: "FOOD-001",
      regular_price: 14.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Food",
          value: "food",
          icon: UtensilsIcon,
          slug: "food",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "jane_smith",
      created_at: "2024-02-09",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_h7i8j9",
      name: "Mountain Bike Pro 21",
      slug: "mountain-bike-pro-21",
      sku: "SPRT-003",
      regular_price: 499.0,
      sale_price: 449.0,
      discount: 10,
      stock_status: "OUT_OF_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        {
          label: "Automotive",
          value: "automotive",
          icon: CarIcon,
          slug: "automotive",
        },
      ],
      created_by: "admin",
      created_at: "2024-02-11",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_k1l2m3",
      name: "Wooden Bookshelf 5-Tier",
      slug: "wooden-bookshelf-5-tier",
      sku: "HOME-003",
      regular_price: 149.0,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Books", value: "books", icon: BookIcon, slug: "books" },
      ],
      created_by: "john_doe",
      created_at: "2024-02-13",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_n4o5p6",
      name: "Vitamin C Supplement 1000mg",
      slug: "vitamin-c-supplement-1000mg",
      sku: "HLTH-001",
      regular_price: 22.5,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Health",
          value: "health",
          icon: HeartIcon,
          slug: "health",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "admin",
      created_at: "2024-02-15",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_q7r8s9",
      name: "Travel Backpack 40L",
      slug: "travel-backpack-40l",
      sku: "TRVL-001",
      regular_price: 79.99,
      sale_price: 64.99,
      discount: 18,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Travel",
          value: "travel",
          icon: GlobeIcon,
          slug: "travel",
          isPrimary: true,
        },
        { label: "Sports", value: "sports", icon: DumbbellIcon, slug: "sports" },
      ],
      created_by: "jane_smith",
      created_at: "2024-02-17",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_t1u2v3",
      name: "Non-Stick Frying Pan Set",
      slug: "non-stick-frying-pan-set",
      sku: "HOME-004",
      regular_price: 54.99,
      stock_status: "ON_BACK_ORDER",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "admin",
      created_at: "2024-02-19",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_w4x5y6",
      name: "JavaScript: The Good Parts",
      slug: "javascript-the-good-parts",
      sku: "BOOK-001",
      regular_price: 29.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Books",
          value: "books",
          icon: BookIcon,
          slug: "books",
          isPrimary: true,
        },
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-02-21",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_z7a8b9",
      name: "Car Dash Cam 4K",
      slug: "car-dash-cam-4k",
      sku: "AUTO-001",
      regular_price: 89.99,
      sale_price: 74.99,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Automotive",
          value: "automotive",
          icon: CarIcon,
          slug: "automotive",
          isPrimary: true,
        },
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
        },
      ],
      created_by: "jane_smith",
      created_at: "2024-02-23",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_c1d2e3",
      name: "Resistance Bands Set",
      slug: "resistance-bands-set",
      sku: "SPRT-004",
      regular_price: 18.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-02-25",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_f4g5h6",
      name: "Wool Blend Overcoat",
      slug: "wool-blend-overcoat",
      sku: "CLTH-002",
      regular_price: 189.0,
      sale_price: 159.0,
      discount: 15,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Clothing",
          value: "clothing",
          icon: ShirtIcon,
          slug: "clothing",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-02-27",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_i7j8k9",
      name: "Espresso Machine Deluxe",
      slug: "espresso-machine-deluxe",
      sku: "HOME-005",
      regular_price: 299.99,
      sale_price: 249.99,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "jane_smith",
      created_at: "2024-03-01",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_l1m2n3",
      name: "USB-C Hub 7-in-1",
      slug: "usb-c-hub-7-in-1",
      sku: "ELEC-005",
      regular_price: 44.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "admin",
      created_at: "2024-03-03",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_o4p5q6",
      name: "Protein Powder Chocolate",
      slug: "protein-powder-chocolate",
      sku: "HLTH-002",
      regular_price: 49.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Health",
          value: "health",
          icon: HeartIcon,
          slug: "health",
          isPrimary: true,
        },
        { label: "Sports", value: "sports", icon: DumbbellIcon, slug: "sports" },
      ],
      created_by: "john_doe",
      created_at: "2024-03-05",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_r7s8t9",
      name: "Linen Bedsheet Set King",
      slug: "linen-bedsheet-set-king",
      sku: "HOME-006",
      regular_price: 89.0,
      stock_status: "OUT_OF_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "jane_smith",
      created_at: "2024-03-07",
      status: { value: "TRASHED", label: "Trashed", level: "DESTRUCTIVE" },
    },
    {
      id: "prod_u1v2w3",
      name: "Passport Holder RFID",
      slug: "passport-holder-rfid",
      sku: "TRVL-002",
      regular_price: 16.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Travel",
          value: "travel",
          icon: GlobeIcon,
          slug: "travel",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "admin",
      created_at: "2024-03-09",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_x4y5z6",
      name: "Noise Isolating Earbuds",
      slug: "noise-isolating-earbuds",
      sku: "ELEC-006",
      regular_price: 39.99,
      sale_price: 29.99,
      discount: 25,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        { label: "Travel", value: "travel", icon: GlobeIcon, slug: "travel" },
      ],
      created_by: "john_doe",
      created_at: "2024-03-11",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_a2b3c4",
      name: "Cast Iron Skillet 12in",
      slug: "cast-iron-skillet-12in",
      sku: "HOME-007",
      regular_price: 34.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "jane_smith",
      created_at: "2024-03-13",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_d5e6f7",
      name: "Car Seat Cushion Memory Foam",
      slug: "car-seat-cushion-memory-foam",
      sku: "AUTO-002",
      regular_price: 29.99,
      stock_status: "ON_BACK_ORDER",
      categories: [
        {
          label: "Automotive",
          value: "automotive",
          icon: CarIcon,
          slug: "automotive",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-03-15",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_g8h9i1",
      name: "Graphic Novel Collection Vol 1",
      slug: "graphic-novel-collection-vol-1",
      sku: "BOOK-002",
      regular_price: 24.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Books",
          value: "books",
          icon: BookIcon,
          slug: "books",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-03-17",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_j2k3l4",
      name: "Swimming Goggles Pro",
      slug: "swimming-goggles-pro",
      sku: "SPRT-005",
      regular_price: 22.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "jane_smith",
      created_at: "2024-03-19",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_m5n6o7",
      name: "Wireless Charging Pad 15W",
      slug: "wireless-charging-pad-15w",
      sku: "ELEC-007",
      regular_price: 27.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "admin",
      created_at: "2024-03-21",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_p8q9r1",
      name: "Floral Maxi Dress",
      slug: "floral-maxi-dress",
      sku: "CLTH-003",
      regular_price: 44.95,
      sale_price: 34.95,
      discount: 22,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Clothing",
          value: "clothing",
          icon: ShirtIcon,
          slug: "clothing",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-03-23",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_s2t3u4",
      name: "Foam Roller Deep Tissue",
      slug: "foam-roller-deep-tissue",
      sku: "SPRT-006",
      regular_price: 19.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-03-25",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_v5w6x7",
      name: "Luggage Set 3-Piece",
      slug: "luggage-set-3-piece",
      sku: "TRVL-003",
      regular_price: 199.0,
      sale_price: 169.0,
      discount: 15,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Travel",
          value: "travel",
          icon: GlobeIcon,
          slug: "travel",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-03-27",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_y8z9a2",
      name: "Car Phone Mount Magnetic",
      slug: "car-phone-mount-magnetic",
      sku: "AUTO-003",
      regular_price: 14.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Automotive",
          value: "automotive",
          icon: CarIcon,
          slug: "automotive",
          isPrimary: true,
        },
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
        },
      ],
      created_by: "jane_smith",
      created_at: "2024-03-29",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_b3c4d5",
      name: "Air Fryer 5.8Qt",
      slug: "air-fryer-5-8qt",
      sku: "HOME-008",
      regular_price: 119.99,
      sale_price: 99.99,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "john_doe",
      created_at: "2024-04-01",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_e6f7g8",
      name: "Portable Power Bank 20000mAh",
      slug: "portable-power-bank-20000mah",
      sku: "ELEC-008",
      regular_price: 39.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        { label: "Travel", value: "travel", icon: GlobeIcon, slug: "travel" },
      ],
      created_by: "admin",
      created_at: "2024-04-03",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_h9i1j2",
      name: "Adjustable Dumbbell Set",
      slug: "adjustable-dumbbell-set",
      sku: "SPRT-007",
      regular_price: 159.0,
      sale_price: 139.0,
      discount: 12,
      stock_status: "OUT_OF_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "john_doe",
      created_at: "2024-04-05",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_k3l4m5",
      name: "Bamboo Cutting Board Set",
      slug: "bamboo-cutting-board-set",
      sku: "HOME-009",
      regular_price: 27.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "jane_smith",
      created_at: "2024-04-07",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_n6o7p8",
      name: "Electric Toothbrush Sonic",
      slug: "electric-toothbrush-sonic",
      sku: "HLTH-003",
      regular_price: 69.99,
      sale_price: 54.99,
      discount: 21,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Health",
          value: "health",
          icon: HeartIcon,
          slug: "health",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-04-09",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_q9r1s2",
      name: "4K Action Camera Waterproof",
      slug: "4k-action-camera-waterproof",
      sku: "ELEC-009",
      regular_price: 149.99,
      sale_price: 119.99,
      discount: 20,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        { label: "Travel", value: "travel", icon: GlobeIcon, slug: "travel" },
      ],
      created_by: "admin",
      created_at: "2024-04-11",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_t3u4v5",
      name: "Canvas Tote Bag Large",
      slug: "canvas-tote-bag-large",
      sku: "SHOP-002",
      regular_price: 12.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
          isPrimary: true,
        },
        { label: "Travel", value: "travel", icon: GlobeIcon, slug: "travel" },
      ],
      created_by: "jane_smith",
      created_at: "2024-04-13",
      status: { value: "TRASHED", label: "Trashed", level: "DESTRUCTIVE" },
    },
    {
      id: "prod_w6x7y8",
      name: "Gaming Mouse RGB 16000 DPI",
      slug: "gaming-mouse-rgb-16000-dpi",
      sku: "ELEC-010",
      regular_price: 59.99,
      sale_price: 49.99,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        {
          label: "Shopping",
          value: "shopping",
          icon: ShoppingBagIcon,
          slug: "shopping",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-04-15",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_z9a1b2",
      name: "Neck Pillow Travel Memory Foam",
      slug: "neck-pillow-travel-memory-foam",
      sku: "TRVL-004",
      regular_price: 23.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Travel",
          value: "travel",
          icon: GlobeIcon,
          slug: "travel",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "john_doe",
      created_at: "2024-04-17",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_c4d5e6",
      name: "Standing Desk Converter",
      slug: "standing-desk-converter",
      sku: "HOME-010",
      regular_price: 89.99,
      sale_price: 74.99,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Home",
          value: "home",
          icon: HomeIcon,
          slug: "home",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "jane_smith",
      created_at: "2024-04-19",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_f7g8h9",
      name: "Winter Puffer Jacket",
      slug: "winter-puffer-jacket",
      sku: "CLTH-004",
      regular_price: 119.0,
      sale_price: 99.0,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Clothing",
          value: "clothing",
          icon: ShirtIcon,
          slug: "clothing",
          isPrimary: true,
        },
        { label: "Travel", value: "travel", icon: GlobeIcon, slug: "travel" },
      ],
      created_by: "admin",
      created_at: "2024-04-21",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_i2j3k4",
      name: "Monitor 27in 144Hz IPS",
      slug: "monitor-27in-144hz-ips",
      sku: "ELEC-011",
      regular_price: 329.0,
      sale_price: 299.0,
      discount: 9,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
          isPrimary: true,
        },
        { label: "Home", value: "home", icon: HomeIcon, slug: "home" },
      ],
      created_by: "jane_smith",
      created_at: "2024-04-23",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_l5m6n7",
      name: "Collagen Peptides Powder",
      slug: "collagen-peptides-powder",
      sku: "HLTH-004",
      regular_price: 36.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Health",
          value: "health",
          icon: HeartIcon,
          slug: "health",
          isPrimary: true,
        },
        { label: "Food", value: "food", icon: UtensilsIcon, slug: "food" },
      ],
      created_by: "jane_smith",
      created_at: "2024-04-25",
      status: { value: "DRAFT", label: "Draft", level: "WARNING" },
    },
    {
      id: "prod_o8p9q1",
      name: "Smoothie Blender Personal",
      slug: "smoothie-blender-personal",
      sku: "FOOD-002",
      regular_price: 44.99,
      sale_price: 36.99,
      discount: 17,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Food",
          value: "food",
          icon: UtensilsIcon,
          slug: "food",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "jane_smith",
      created_at: "2024-04-27",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_r2s3t4",
      name: "Python Programming Guide",
      slug: "python-programming-guide",
      sku: "BOOK-003",
      regular_price: 39.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Books",
          value: "books",
          icon: BookIcon,
          slug: "books",
          isPrimary: true,
        },
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
        },
      ],
      created_by: "john_doe",
      created_at: "2024-04-29",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_u5v6w7",
      name: "Car Jump Starter Portable",
      slug: "car-jump-starter-portable",
      sku: "AUTO-004",
      regular_price: 59.99,
      sale_price: 49.99,
      discount: 16,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Automotive",
          value: "automotive",
          icon: CarIcon,
          slug: "automotive",
          isPrimary: true,
        },
        {
          label: "Electronics",
          value: "electronics",
          icon: MonitorIcon,
          slug: "electronics",
        },
      ],
      created_by: "admin",
      created_at: "2024-05-01",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
    {
      id: "prod_x8y9z1",
      name: "Boxing Gloves Training 14oz",
      slug: "boxing-gloves-training-14oz",
      sku: "SPRT-008",
      regular_price: 36.99,
      stock_status: "IN_STOCK",
      categories: [
        {
          label: "Sports",
          value: "sports",
          icon: DumbbellIcon,
          slug: "sports",
          isPrimary: true,
        },
        { label: "Health", value: "health", icon: HeartIcon, slug: "health" },
      ],
      created_by: "admin",
      created_at: "2024-05-03",
      status: { value: "PUBLISHED", label: "Published", level: "SAFE" },
    },
  ];

export const ATTR_TYPE_OPTIONS: (Omit<
  CellSelectorValuesType<string>,
  "value"
> & { value: "COLOR" | "TEXT" })[] = [
    { value: "COLOR", label: "Color" },
    { value: "TEXT", label: "Text" },
  ];

export const DUMMY_PRODUCT_CATEGORIES = [
  { label: "Electronics", value: "electronics" },
  { label: "Home & Garden", value: "home-garden" },
  { label: "Beauty & Health", value: "beauty-health" },
  { label: "Toys & Hobbies", value: "toys-hobbies" },
  { label: "Automotive", value: "automotive" },
];

export const DUMMY_PRODUCT_TAGS = [
  { label: "New Arrival", value: "new-arrival" },
  { label: "Best Seller", value: "best-seller" },
  { label: "Limited Edition", value: "limited-edition" },
  { label: "Discounted", value: "discounted" },
  { label: "Eco-Friendly", value: "eco-friendly" },
  { label: "Free Shipping", value: "free-shipping" },
  { label: "Handmade", value: "handmade" },
  { label: "Refurbished", value: "refurbished" },
  { label: "Trending", value: "trending" },
  { label: "Seasonal", value: "seasonal" },
  { label: "Clearance", value: "clearance" },
  { label: "Premium", value: "premium" },
];

export const DUMMY_PRODUCT_BRANDS = [
  { label: "Apple", value: "apple" },
  { label: "Samsung", value: "samsung" },
  { label: "Sony", value: "sony" },
  { label: "Nike", value: "nike" },
  { label: "Adidas", value: "adidas" },
  { label: "Logitech", value: "logitech" },
  { label: "Dell", value: "dell" },
  { label: "HP", value: "hp" },
  { label: "Asus", value: "asus" },
  { label: "Microsoft", value: "microsoft" },
  { label: "Bosch", value: "bosch" },
  { label: "L'Oréal", value: "loreal" },
  { label: "Xiaomi", value: "xiaomi" },
  { label: "Razer", value: "razer" },
  { label: "Corsair", value: "corsair" },
];
