export const API_BASE_URI = process.env.NEXT_PUBLIC_API_BASE_URI;
export const ALGOLIA_SEARCH_API = process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_API;
export const ALGOLIA_APPLICATION_ID =
  process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID;
