import { FileType } from "@fluctux/types";
import { SVGProps } from "react";
import {
  Bash,
  C,
  Cpp,
  CSS,
  Docker,
  Git,
  HTML5,
  JavaScript,
  JSON,
  Markdown,
  MdxIcon,
  Nginx,
  Npm,
  Prettier,
  ReactJSX,
  ReactTsx,
  Text,
  Turbo,
  TypeScript,
} from "@fluctux/ui";
export const GetIconByLanguage: Record<
  FileType,
  React.ComponentType<SVGProps<SVGSVGElement>>
> = {
  js: JavaScript,
  ts: TypeScript,
  tsx: ReactTsx,
  jsx: ReactJSX,
  html: HTML5,
  css: CSS,
  json: JSON,
  bash: Bash,
  nginx: Nginx,
  docker: Docker,
  git: Git,
  cpp: Cpp,
  c: C,
  md: Markdown,
  mdx: MdxIcon,
  text: Text,
  npm: Npm,
  turbo: Turbo,
  prettier: Prettier,
};
