name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      
permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        with:
          types: |
            hotfix: Immediate fix for critical bugs affecting production
            release: Prepares codebase for a stable production deployment
            feat: A new feature
            fix: A bug fix
            docs: Documentation only changes
            style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
            refactor: A code change that neither fixes a bug nor adds a feature
            perf: A code change that improves performance
            test: Adding missing tests or correcting existing tests
            build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
            ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
            chore: Other changes that don't modify src or test files
            revert: Reverts a previous commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼
            
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:   
          header: pr-title-lint-error
          delete: true