name: PR - Preview Web Docker Image

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  Preview:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      # Database
      MONGO_URI: ${{ secrets.MONGO_URI }}

      # Base URI
      NEXT_PUBLIC_API_BASE_URI: ${{ vars.NEXT_PUBLIC_API_BASE_URI }}

      # NextAuth
      AUTHJS_SECRET: ${{ secrets.AUTHJS_SECRET }}

      # Github
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_RAW_CONTENT_API: ${{ vars.GH_RAW_CONTENT_API }}
      GH_AUTH_DOC_API: ${{ vars.GH_AUTH_DOC_API }}

      # Algolia
      NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: ${{ vars.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID }}
      NEXT_PUBLIC_ALGOLIA_SEARCH_API: ${{ vars.NEXT_PUBLIC_ALGOLIA_SEARCH_API }}
      NEXT_ALGOLIA_WRITE_API: ${{ secrets.NEXT_ALGOLIA_WRITE_API }}

      # Arcjet
      ARCJET_KEY: ${{ secrets.ARCJET_KEY }}

      # Docker
      DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

      # Branch
      NEXT_PUBLIC_BRANCH: contributing

      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      TURBO_TELEMETRY_DISABLED: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
