name: Build / Push - Docker Images

on:
  push:
    branches:
      - main

env:
  # Branch
  NEXT_PUBLIC_BRANCH: ${{ vars.NEXT_PUBLIC_BRANCH }}
  # Docker
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  # Turbo
  TURBO_TEAM: ${{secrets.TURBO_TEAM}}
  TURBO_TOKEN: ${{secrets.TURBO_TOKEN}}
  # Algolia
  NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: ${{ vars.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID }}
  NEXT_PUBLIC_ALGOLIA_SEARCH_API: ${{ vars.NEXT_PUBLIC_ALGOLIA_SEARCH_API }}
  NEXT_ALGOLIA_WRITE_API: ${{ secrets.NEXT_ALGOLIA_WRITE_API }}
  # Github
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  # Database
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  fluctux-web:
    runs-on: ubuntu-latest
    env:
      # Base URI
      NEXT_PUBLIC_API_BASE_URI: ${{ vars.NEXT_PUBLIC_API_BASE_URI }}
      # NextAuth
      AUTHJS_SECRET: ${{ secrets.AUTHJS_SECRET }}
      # Github
      GH_RAW_CONTENT_API: ${{ vars.GH_RAW_CONTENT_API }}
      GH_AUTH_DOC_API: ${{ vars.GH_AUTH_DOC_API }}
      # Arcjet
      ARCJET_KEY: ${{ secrets.ARCJET_KEY }}

    steps:
      - name: Checkout fluctux repository
        uses: actions/checkout@v4

      - name: Build Fluctux Web Image
        run: |
          docker build --no-cache -t ${DOCKER_USERNAME}/fluctux-web:latest \
            --build-arg MONGO_URI=${MONGO_URI} \
            --build-arg NEXT_PUBLIC_API_BASE_URI=${NEXT_PUBLIC_API_BASE_URI} \
            --build-arg AUTHJS_SECRET=${AUTHJS_SECRET} \
            --build-arg NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${NEXT_PUBLIC_ALGOLIA_APPLICATION_ID} \
            --build-arg NEXT_PUBLIC_ALGOLIA_SEARCH_API=${NEXT_PUBLIC_ALGOLIA_SEARCH_API} \
            --build-arg NEXT_ALGOLIA_WRITE_API=${NEXT_ALGOLIA_WRITE_API} \
            --build-arg ARCJET_KEY=${ARCJET_KEY} \
            --build-arg GH_TOKEN=${GH_TOKEN} \
            --build-arg GH_RAW_CONTENT_API=${GH_RAW_CONTENT_API} \
            --build-arg GH_AUTH_DOC_API=${GH_AUTH_DOC_API} \
            --build-arg NEXT_PUBLIC_BRANCH=${NEXT_PUBLIC_BRANCH}\
            --build-arg TURBO_TEAM=${TURBO_TEAM}\
            --build-arg TURBO_TOKEN=${TURBO_TOKEN}\
            -f apps/web/Dockerfile .

      - name: Push Fluctux Web Image
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_ACCESS_TOKEN}
          docker push ${DOCKER_USERNAME}/fluctux-web:latest

  fluctux-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fluctux repository
        uses: actions/checkout@v4

      - name: Build Fluctux Main Image
        run: |
          docker build -t ${DOCKER_USERNAME}/fluctux-main:latest \
          --build-arg NEXT_PUBLIC_BRANCH=${NEXT_PUBLIC_BRANCH} \
          -f apps/main/Dockerfile .
      - name: Push Fluctux Main Image
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_ACCESS_TOKEN}
          docker push ${DOCKER_USERNAME}/fluctux-main:latest

  fluctux-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fluctux repository
        uses: actions/checkout@v4

      - name: Build Fluctux Admin Image
        run: |
          docker build -t ${DOCKER_USERNAME}/fluctux-admin:latest \
          --build-arg NEXT_PUBLIC_BRANCH=${NEXT_PUBLIC_BRANCH} \
          -f apps/admin/Dockerfile .
      - name: Push Fluctux Main Image
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_ACCESS_TOKEN}
          docker push ${DOCKER_USERNAME}/fluctux-admin:latest

  fluctux-backend:
    runs-on: Checkout fluctux repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fluctux repository
        uses: actions/checkout@v4
